const OK_SUCCESS_CODE = 200;
const CREATED_SUCCESS_CODE = 201;

const BADREQUEST_ERROR_CODE = 400;
const UNAUTHORIZED_ERROR_CODE = 401;
const FORBIDDEN_ERROR_CODE = 403;
const NOTFOUND_ERROR_CODE = 404;
const CONFLICT_ERROR_CODE = 409;

const DEFAULT_ERROR_CODE = 500;

module.exports = {
  OK_SUCCESS_CODE,
  CREATED_SUCCESS_CODE,
  BADREQUEST_ERROR_CODE,
  NOTFOUND_ERROR_CODE,
  DEFAULT_ERROR_CODE,
  UNAUTHORIZED_ERROR_CODE,
  FORBIDDEN_ERROR_CODE,
  CONFLICT_ERROR_CODE,
};
